theme = "coder" # set the theme

[params] # theme parameters
    author = "AiEnable" # author's name
    info = "DevOps | Development | VAPT | AWS | ReCoding | Scaling | Cloud" # author's job title or info
    description = "John Doe's personal website" # site description
    keywords = "blog,developer,personal" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = true
    hideCopyright = false
    math=true
    
# Social links
#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/johndoe/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/johndoe/"
#[[params.social]]
#    name = "LinkedIn"
#    weight = 3
#    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
